pref(
    'vivipos.fec.settings.controlpanels.config.skypay_promotion_settings.icon',
    'chrome://skypay_promotion/skin/images/skypay_promotion_Logo.png'
);
pref(
    'vivipos.fec.settings.controlpanels.config.skypay_promotion_settings.label',
    'chrome://skypay_promotion/locale/messages.properties'
);
pref(
    'vivipos.fec.settings.controlpanels.config.skypay_promotion_settings.path',
    'chrome://skypay_promotion/content/settings.xul'
);
pref(
    'vivipos.fec.settings.controlpanels.config.skypay_promotion_settings.roles',
    'acl_skypay_promotion_settings'
);
